name: WSPS
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.7
  - jupyter
  - pip
  - geopandas
  - pandas == 0.24
  - matplotlib
  - scipy
  - xarray
  - cdsapi
  - pip:
    - supy == 2019.4.15
    - supy-driver == 2018rc8
    - tzwhere
    - timezonefinder
    - tqdm