var milestones = [
   {
      "url": "https://api.github.com/repos/sunt05/WRF-SUEWS/milestones/1",
      "html_url": "https://github.com/sunt05/WRF-SUEWS/milestone/1",
      "labels_url": "https://api.github.com/repos/sunt05/WRF-SUEWS/milestones/1/labels",
      "id": 3282489,
      "number": 1,
      "title": "design",
      "description": "",
      "creator": {
         "login": "sunt05",
         "id": 1802656,
         "avatar_url": "https://avatars3.githubusercontent.com/u/1802656?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/sunt05",
         "html_url": "https://github.com/sunt05",
         "followers_url": "https://api.github.com/users/sunt05/followers",
         "following_url": "https://api.github.com/users/sunt05/following{/other_user}",
         "gists_url": "https://api.github.com/users/sunt05/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/sunt05/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/sunt05/subscriptions",
         "organizations_url": "https://api.github.com/users/sunt05/orgs",
         "repos_url": "https://api.github.com/users/sunt05/repos",
         "events_url": "https://api.github.com/users/sunt05/events{/privacy}",
         "received_events_url": "https://api.github.com/users/sunt05/received_events",
         "type": "User",
         "site_admin": false
      },
      "open_issues": 3,
      "closed_issues": 0,
      "state": "open",
      "created_at": "2018-04-19T20:21:18Z",
      "updated_at": "2018-04-19T20:22:35Z",
      "due_on": "2018-04-24T07:00:00Z",
      "closed_at": null
   },
   {
      "url": "https://api.github.com/repos/sunt05/WRF-SUEWS/milestones/3",
      "html_url": "https://github.com/sunt05/WRF-SUEWS/milestone/3",
      "labels_url": "https://api.github.com/repos/sunt05/WRF-SUEWS/milestones/3/labels",
      "id": 3282564,
      "number": 3,
      "title": "alpha dev",
      "description": "first stage development by connecting SUEWS and WRF with simple interface and basic physics modules.",
      "creator": {
         "login": "sunt05",
         "id": 1802656,
         "avatar_url": "https://avatars3.githubusercontent.com/u/1802656?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/sunt05",
         "html_url": "https://github.com/sunt05",
         "followers_url": "https://api.github.com/users/sunt05/followers",
         "following_url": "https://api.github.com/users/sunt05/following{/other_user}",
         "gists_url": "https://api.github.com/users/sunt05/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/sunt05/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/sunt05/subscriptions",
         "organizations_url": "https://api.github.com/users/sunt05/orgs",
         "repos_url": "https://api.github.com/users/sunt05/repos",
         "events_url": "https://api.github.com/users/sunt05/events{/privacy}",
         "received_events_url": "https://api.github.com/users/sunt05/received_events",
         "type": "User",
         "site_admin": false
      },
      "open_issues": 2,
      "closed_issues": 0,
      "state": "open",
      "created_at": "2018-04-19T20:59:04Z",
      "updated_at": "2018-04-19T21:29:13Z",
      "due_on": "2018-04-25T07:00:00Z",
      "closed_at": null
   },
   {
      "url": "https://api.github.com/repos/sunt05/WRF-SUEWS/milestones/2",
      "html_url": "https://github.com/sunt05/WRF-SUEWS/milestone/2",
      "labels_url": "https://api.github.com/repos/sunt05/WRF-SUEWS/milestones/2/labels",
      "id": 3282517,
      "number": 2,
      "title": "alpha test",
      "description": "first stage test: mostly for testing the connectivity between SUEWS and WRF code; would be great if some physics can be tested as well.  ",
      "creator": {
         "login": "sunt05",
         "id": 1802656,
         "avatar_url": "https://avatars3.githubusercontent.com/u/1802656?v=4",
         "gravatar_id": "",
         "url": "https://api.github.com/users/sunt05",
         "html_url": "https://github.com/sunt05",
         "followers_url": "https://api.github.com/users/sunt05/followers",
         "following_url": "https://api.github.com/users/sunt05/following{/other_user}",
         "gists_url": "https://api.github.com/users/sunt05/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/sunt05/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/sunt05/subscriptions",
         "organizations_url": "https://api.github.com/users/sunt05/orgs",
         "repos_url": "https://api.github.com/users/sunt05/repos",
         "events_url": "https://api.github.com/users/sunt05/events{/privacy}",
         "received_events_url": "https://api.github.com/users/sunt05/received_events",
         "type": "User",
         "site_admin": false
      },
      "open_issues": 2,
      "closed_issues": 0,
      "state": "open",
      "created_at": "2018-04-19T20:36:36Z",
      "updated_at": "2018-04-19T20:42:55Z",
      "due_on": "2018-04-27T07:00:00Z",
      "closed_at": null
   }
];
var status = "fresh";