name: doxygen

on: [push]

jobs:
  doxygen:

    # runs-on: macOS-latest
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        submodules: yes
        token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Checkout submodules
    #   uses: textbook/git-checkout-submodule-action@2.0.0
    # - name: install
    #   run: sudo apt-get install graphviz doxygen-gui
    # - name: Build Doxygen pages
    #   run: |
    #    cd docs
    #    ./deploy-doxygen-gh-pages.sh
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@1.1.3
      env:
       FOLDER: docs/doxygenoutput/html
       BRANCH: gh-pages
       BUILD_SCRIPT: apt-get install -y graphviz doxygen-gui; cd docs; doxygen; cd ..
       ACCESS_TOKEN: ${{ secrets.GH_PAT }}
